### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by rwarbelow** [ayladharamsey/mod_0_skills#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [x] I named my directories correctly. 
- [x] I named my files correctly.
- [x] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
> This is a good start, but we'd like to see another sub-layer to know that you're able to continue breaking down steps.
- [] I added and committed my changes with a properly formatted commit message starting with a verb and a capital letter.
> Make sure that your verbs are in present tense, not past tense (so use `Add` instead of `Added`). 
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [x] I structured and named my directories and files correctly.
- [x] The three attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [x] The three methods I chose for **Class #1** represent behaviors or actions.
> For the `Add_Employee` and `Delete_Employee` methods, these sound like methods more suited to a `Team` or `Organization` or `Business` class. Otherwise, it sounds like you're adding an employee to an employee (or deleting an employee from an employee) which doesn't make a lot of sense.
- [x] I described what the methods do in **Class 1**.
- [x] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 
> Use present tense verb in commit message

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
> (See notes from above)
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 
> Use present tense verb in commit message

Class #2 Checklist
- [x] The three attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [x] The three methods I chose for **Class #2** represent behaviors or actions.
> (See notes from above -- `Remove_Entree` probably belongs on a `Menu` class, not the actual entree class. You wouldn't remove an entree from an entree.)
- [x] I described what the methods do in **Class 2**.
> I'm a little confused about your `Happy_Hour` method: generally, a method should describe an action. `Happy_Hour` sounds like a noun. Methods that would be actions could be things like `toggle_happy_hour_status` (which changes the boolean attribute from true -> false and vice versa) or `apply_happy_hour_discount` (which applies a percent discount to the price attribute), etc. 
- [x] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 
> Use present tense verb in commit message

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 
> Use present tense verb in commit message

### Assessment Results
- [ ] Technical Ready
- [x] Pending
> One more comment that I didn't know where to put in the rubric :) -- Make sure your class names are singular. For example, `Employee` class instead of `Employees` class, or `Entree` class instead of `Entrees` class. This singularization also helps you think of a class a blueprint for *one* object as opposed to a collection. 
> Next steps:
> Add one more layer of sub-steps to your top down design file.
> Create one more file called class_3.txt and define a class that you would find in a city. Be sure that the methods are all actions of/for that specific class. Create another file called class_3_example_object.txt and give the attributes and methods for a specific object of that class.
- [ ] Not Technical Ready

**Comment by ayladharamsey** [comment]
All updates made! Should I be submitting a new PR?
